@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3MjRlMTdmZS01NmUyLTQ3YTAtOTdlOC1hMjgzODhkN2VjNDIiLCJpYXQiOjE3MjYyNjA5ODQsImV4cCI6MTcyNjI2NDU4NH0.svQ9OuZrc0wO7mWP2lPgZGzcJEuV8abggpTf8pVhMyw
###
POST http://localhost:4500/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "email": "karen@hica.com",
    "password": "innotech"
}
###

GET http://localhost:4500/api/v1/usuarios HTTP/1.1
Authorization: {{token}}
###

GET http://localhost:4500/api/v1/veterinarios HTTP/1.1
Authorization: {{token}}
###

POST http://localhost:4500/api/v1/veterinarios HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "N_de_registro": "12345",
  "Validado": true,
  "deviceId": "abcdef123456",
  "Dependencia": "Veterinaria Central",
  "Foto": null, 
  "userId": "34673aab-428b-4c49-8b02-c80ad8d72cd2"
}

