GET http://localhost:3000/api/v1/usuarios HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMGQxZGE2ZC02Y2RlLTRlY2EtODA2YS02Nzc0ZmQ1MmUxZWIiLCJpYXQiOjE3MjU0MTU5NTUsImV4cCI6MTcyNTQxOTU1NX0.311ORG0VqJeOO85Nd0NUmbRK_ANyc878_hzfCpBD6wI
###
POST http://localhost:3000/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "email": "testuser1@example.com",
    "password": "password123"
}
